addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"


env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: FMTwZH7ntFOy4XRJWcbwXWFJri3QZgcqsJeIiVyXF2OfOafOYnavVREvaM7nzanrE/OFsDLArXOraIPLC40V6OxEXmSHX4x0PPZE4O7A//GySFlohkb

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="portal_partner_merge"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="portal_partner_merge"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="portal_partner_merge"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="portal_partner_merge"

virtualenv:
  system_site_packages: true

install:
  - pip install requests
  - pip install unicodecsv
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
