[project]
name = "odoo-addons-oca-partner-contact"
version = "17.0.20240222.1"
dependencies = [
    "odoo-addon-partner_address_street3>=17.0dev,<17.1dev",
    "odoo-addon-partner_company_type>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_birthdate>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_gender>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_personal_information_page>=17.0dev,<17.1dev",
    "odoo-addon-partner_fax>=17.0dev,<17.1dev",
    "odoo-addon-partner_firstname>=17.0dev,<17.1dev",
    "odoo-addon-partner_identification>=17.0dev,<17.1dev",
    "odoo-addon-partner_ref_unique>=17.0dev,<17.1dev",
    "odoo-addon-partner_second_lastname>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
